#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 # 7 8 9 10

bspc config border_width         5
bspc config focused_border_color "#fba922"
bspc config normal_border_color "#908caa"
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a discord desktop='^2'
bspc rule -a steam desktop='^3'
bspc rule -a Screenkey manage=off
bspc rule -a peek state=floating
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
bspc rule -a imv state=floating center=true
bspc rule -a SimpleScreenRecorder state=floating


feh --bg-fill /home/xinghe/图片/wallhaven-3lepy9.jpg
# feh --randomize --bg-fill ~/Pictures/wallpaper/*
xsetroot -cursor_name left_ptr
mpd &
dunst &
picom &
fcitx5 &
nm-applet &
keymapper &
# $HOME/polybar-collection/launch.sh
$HOME/.config/polybar/launch.sh
